version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1883:1883"
    volumes:
      - "${MOSQUITTO_CONF-./docker/mosquitto/mosquitto.conf}:/mosquitto/config/mosquitto.conf:ro"
      - "${MOSQUITTO_INCLUDE_DIR-./docker/mosquitto/conf.d}:/mosquitto/config/conf.d:ro"
