version: "3.4"

services:
  mosquitto:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: configured
    command: mosquitto -c /mosquitto-with-auth.conf
    environment:
      AUTH_USER: ${AUTH_USER}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      TOPIC_ANONYMOUS: ${TOPIC_ANONYMOUS}
      TOPIC_RESTRICTED: ${TOPIC_RESTRICTED}
    ports:
      - "${SERVER_PORT}:1883"
