version: "3.4"

services:
  mosquitto:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    command: mosquitto -c /mosquitto-with-auth.conf
    environment:
      SERVER_PORT: ${SERVER_PORT}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      TOPIC_ANONYMOUS: ${TOPIC_ANONYMOUS}
      TOPIC_RESTRICTED: ${TOPIC_RESTRICTED}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

