version: "3.4"

services:
  mosquitto:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    command: mosquitto -c /config/mosquitto.conf
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:1883
    # Mount config files, e.g. from local "config" folder
    # volumes:
    #   - ./config:/config:ro